;;; elfeed/config.el --- RSS/atom feed manager -*- lexical-binding: t -*-
;;; Commentary:
;;; Code:

(use-package elfeed
  :ensure t
  :bind ("C-x e" . elfeed)
  :config
  (setq elfeed-feeds
        '(("http://nullprogram.com/feed/" blog)
          ("https://planet.emacslife.com/atom.xml" blog emacs)
          ("https://sophiebos.io/index.xml" blog)
          ("https://sigkill.dk/atom.xml" blog)
          ("https://xkcd.com/rss.xml" comics)
          ("https://danluu.com/atom.xml" blog)
          ("https://drewdevault.com/blog/index.xml" blog)
          ("https://scripter.co/index.xml" blog emacs)
          ("https://pharr.org/matt/blog/feed.xml" blog)
          ("https://writing.kemitchell.com/feed.xml" blog)
          ("https://pythonspeed.com/atom.xml" blog)
          ("https://devblog.archlinux.page/atom.xml" blog arch)
          ("https://ploum.net/atom_en.xml" blog)
          ("https://protesilaos.com/master.xml" blog)
          ("https://noonker.github.io/index.xml" blog)
          ("https://www.schneier.com/feed/atom/" blog security)
          ("https://simon.peytonjones.org/feed.xml" blog research)
          ("https://johnrakestraw.com/index.xml" blog)
          ("https://weeklyrust.substack.com/feed" blog rust)
          ("https://www.rousette.org.uk/index.xml" blog)
          ("https://notthebe.ee/rss.xml" blog tech)
          ("https://www.youtube.com/feeds/videos.xml?channel_id=UCCbfB3cQtkEAiKfdRQnfQvw" youtube)
          ("https://www.youtube.com/feeds/videos.xml?channel_id=UC8bSNxb8Oc7b28N2TTrQC1g" youtube)
          ("https://www.youtube.com/feeds/videos.xml?channel_id=UCcoO-8J0EYQHGPFQqwmAzVQ" youtube)
          ("https://www.youtube.com/feeds/videos.xml?channel_id=UCXGR70CkW_pXb8n52LzCCRw" youtube)
          ("https://www.youtube.com/feeds/videos.xml?channel_id=UCE1jXbVAGJQEORz9nZqb5bQ" youtube)
          ("https://www.youtube.com/feeds/videos.xml?channel_id=UCUMwY9iS8oMyWDYIe6_RmoA" youtube)
          ("https://www.youtube.com/feeds/videos.xml?channel_id=UCzJ3EGLJbFcHJJ8r1rNGSJQ" youtube)
          ("https://www.youtube.com/feeds/videos.xml?channel_id=UC-ufRLYrXxrIEApGn9VG5pQ" youtube)
          ("https://www.youtube.com/feeds/videos.xml?channel_id=UCEQ7KR9enYdQsB6kcMnw0NA" youtube)
          ("https://www.youtube.com/feeds/videos.xml?channel_id=UCR-DXc1voovS8nhAvccRZhg" youtube)
          ("https://www.youtube.com/feeds/videos.xml?channel_id=UCwHwDuNd9lCdA7chyyquDXw" youtube)
          ("https://www.youtube.com/feeds/videos.xml?channel_id=UCgdTVe88YVSrOZ9qKumhULQ" youtube)
          ("https://www.youtube.com/feeds/videos.xml?channel_id=UCq8ZAAsI89IoJ-fn1gYpO3g" youtube)
          ("https://www.youtube.com/feeds/videos.xml?channel_id=UCHnyfMqiRRG1u-2MsSQLbXA" youtube)
          ("https://www.youtube.com/feeds/videos.xml?channel_id=UC7EUErrXAtCjdr8-SuLaGow" youtube)
          ("https://www.youtube.com/feeds/videos.xml?channel_id=UCsXVk37bltHxD1rDPwtNM8Q" youtube)
          ("https://www.youtube.com/feeds/videos.xml?channel_id=UCV6g95OBbVtFmN9uiJzkFqQ" youtube)
          ("https://www.youtube.com/feeds/videos.xml?channel_id=UCtJrxXDeJ9bINlrW-RPBI9Q" youtube)
          ("https://www.youtube.com/feeds/videos.xml?channel_id=UC4dxXZQq-ofAadUWbqhoceQ" youtube)
          ("https://www.youtube.com/feeds/videos.xml?channel_id=UC9-y-6csu5WGm29I7JiwpnA" youtube)
          ("https://www.youtube.com/feeds/videos.xml?channel_id=UCbfYPyITQ-7l4upoX8nvctg" youtube)
          ("https://www.youtube.com/feeds/videos.xml?channel_id=UCAbAsEZ-0LccTNbl8r-3EaQ" youtube)
          ("https://www.youtube.com/feeds/videos.xml?channel_id=UC_iD0xppBwwsrM9DegC5cQQ" youtube)
          ("https://www.youtube.com/feeds/videos.xml?channel_id=UCSp-OaMpsO8K0KkOqyBl7_w" youtube)
          ("https://www.youtube.com/feeds/videos.xml?channel_id=UCj74rJ9Lgl3WTngq675wxKg" youtube)
          ("https://www.youtube.com/feeds/videos.xml?channel_id=UCy0tKL1T7wFoYcxCe0xjN6Q" youtube)
          ("https://www.youtube.com/feeds/videos.xml?channel_id=UC--_DvRzKXtQyVdOWVLUJCA" youtube)
          ("https://www.youtube.com/feeds/videos.xml?channel_id=UC_mmaVYaFmlfdxuKb6U69Yw" youtube))))

(provide 'slp-elfeed)
;;; config.el ends here
